### PR TITLE
Updates to support the TS 3.6.0 beta, and adds a daily run-script 

### PR DESCRIPTION
**Pull request by orta**
- `ts.DiagnosticMessageChain` now supports nested diagnostics, so I moved over the new function from TS.
- Includes #35 - which I'll close
- Adds a script for updating the version to a daily build from the TS daily build

### CODE REVIEW

**Comment by orta** [comment]
This is currently blocked because I can't add a pipeline to this repo, so I've applied to join the vscode team in the ms GitHub org

**Comment by orta** [comment]
OK, I've verified this on my own pipelines to be working 👍

**Comment by orta** [comment]
Ah yeah, I remember now, I didn't want to have to send along all of the changes of TypeScript 3.6 in this PR when it was still in a beta phase - and so I didn't ship the package.json change. 

The RC _should_ be today, so I'm happy to have that happen once that that's shipped. I can give it a shot at handling both forms of diagnostics but it's probably not worth it given that it will only be used with 3.6+ form here on out

**Comment by alexandrudima** [comment]
1. The version of `monaco-typescript` in `package.json` is in no way related to the version of TypeScript it ships.

2. Sorry for not explaining clearer. While TS 3.6 was in beta, I could not accept the changes unless the changes covered TS 3.5. Now that TS 3.6 is released (and adopted via `package.json`), we don't need to have TS 3.5 compatibility.

**Comment by alexandrudima** [comment]
Thank you! :heart:

**Comment by orta** [comment]
Thank you!

**Pull request merged**
