### PR TITLE
Update TypeScript to 3.7.2

### PR DESCRIPTION
**Pull request by katis**
Updated TypeScript version, ran the `import-typescript` script, and checked that I can use `?.` and assertion functions in the test page.

### CODE REVIEW

**Comment by ulrichb** [comment]
@alexandrudima Pleaaaase. Can't wait for the optional chaining in my Monaco Editor 🐱

**Comment by orta** [comment]
While you're waiting - you can re-use the official builds made for TypeScript. https://www.npmjs.com/package/@typescript-deploys/monaco-editor

**Comment by ulrichb** [comment]
@orta Thanks for the hint. Does `@typescript-deploys/monaco-editor` work with the [webpack plugin](https://github.com/microsoft/monaco-editor-webpack-plugin)?

**Comment by ulrichb** [comment]
... probably not, ... see https://github.com/microsoft/monaco-editor-webpack-plugin/blob/1d1473de8ed44d999cb1f6515ce00a4fa67e87ab/index.js#L20-L22

**Comment by orta** [comment]
I don't use the webpack plugin, so I'm not quite sure what you're showing me - but these are more or less vanilla copies of this repo which are deployed in the same process

**Comment by alexdima** [comment]
Thank you! :heart:

**Comment by ulrichb** [comment]
Thank you, @alexdima !!

**Pull request merged**
