### PR TITLE
Adds a CodeAction provider to support fixits

### PR DESCRIPTION
**Pull request by orta**
gifs 2019-08-29 13_35_46

Adds the ability to showcase code actions and suggestions in Monaco-typescript - woo! Now it's feasible for the TS team to showcase code edits :D

### CODE REVIEW

**Comment by orta** [comment]
I've looked at this a second time but not entirely got the answer. I think what's happening here is that because I send both the edits and a command to run, then the edits are applied but the command after fails which shows that error.

From a look in vscode, it looks like instead it uses a custom command that sends messages which  are more or less just sent straight back to the typescript worker to do the editing changes instead. 

Will take a stab at that

**Comment by orta** [comment]
This... Is tricky. 

The ts/js language implementations have no access to an instance of an editor. To handle the callback in a similar manner to vscode, I need an instance of the editor to register a command for the code actions to run.

There are two routes I can do _as-is_:

1. Add an extra call to `monaco.lanaguges.typescript` which passes in an editor. e.g.
    ```js
    const editor = monaco.editor.create({...})
    monaco.editor.languages.typescript.setup(editor)
    ```
    Which could be used to add the commands and to opt the editor into getting code action support.

2. Use `monaco.editor.onDidCreateEditor` to add the TypeScript command, this means adding it to every instance of the editor regardless of whether you're using TS or not (because a model can change language to typescript at runtime ( I think ) )

Neither are great options, though I may go for the former.

**Comment by spahnke** [comment]
Do you need to register a command here at all? From the documentation in [vscode.d.ts](https://github.com/microsoft/vscode/blob/eb5ec0fd2a9f22a2cac3ba672c2ed9e9b04385b6/src/vs/vscode.d.ts#L2087) I get the impression that edits would be sufficient. At least that's the only thing I supply when hooking up ESLint to Monaco. It would be interesting to know what an additional command would be used for.

**Comment by spahnke** [comment]
Also: The `kind` property has to be set to `"quickfix"`. Otherwise the popup says "No quick fixes available". This is not documented unfortunately and it took me a while to find that (I think I debugged, or looked into the source code).

**Comment by orta** [comment]
> Do you need to register a command here at all?

I do if I want to let _typescript_ handle making the changes to the code (which is what happens in vscode ) - there's no other route for getting the callback that a user has selected it. 

Maybe I can just have a version which just applies the code edits which TypeScript passes and call it at that.

**Comment by orta** [comment]
Screen Recording 2019-10-01 09_11_37

Thanks @spahnke  - I've tried this out on a bunch of our fixits and it works as expected. 

This version doesn't use the TypeScript services to make the changes, but only uses the code edit deltas sent from the original response from the language service which seems to be enough for every fixits I tried from in the typescript test suite.

Should be good to go.

**Comment by alexandrudima** [comment]
This looks great! :heart:

**Comment by orta** [comment]
Woo, thanks @alexandrudima <3

**Pull request merged**
